<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 08/08/17
 * Time: 12:01
 */

namespace BlogBundle\Repository;


/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForList($filter)
    {
        $qb = $this
            ->createQueryBuilder('blogpost')
            ->select('blogpost')
            ->addOrderBy('blogpost.createdAt', 'DESC')
        ;

        if ('only_published' === $filter) {
            $qb->andWhere('blogpost.publishedAt IS NOT NULL');
        }
        if ('only_not_published' === $filter) {
            $qb->andWhere('blogpost.publishedAt IS NULL');
        }


        return $qb->getQuery()->getResult();
    }


    // Depuis le repository BlogPost
    public function getBlogPostWithComments()
    {
        $qb = $this->createQueryBuilder('blogpost')
            ->leftJoin('blogpost.comments.', 'comments')
            ->addSelect('c');

        return $qb->getQuery()
            ->getResult();
    }




}